apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkinci-app       
  namespace: arogocd
spec:
  project: default
  source:
    repoURL: https://github.com/mayur21486/jenkinci.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkinci
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
